version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-service-registry:
    image: gejarajandocker/eureka-service-registry:0.0.1
    ports:
      - "8761:8761"
  cloud-config-server:
    image: gejarajandocker/cloud-config-server:0.0.1
    ports:
      - "9296:9296"
    depends_on:
      - eureka-service-registry
  catalogue-service:
    image: gejarajandocker/catalogue-service:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service-registry
  inventory-service:
    image: gejarajandocker/inventory-service:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - eureka-service-registry
      - product-search-service
      - rabbitmq
  product-search-service:
    image: gejarajandocker/product-search-servicee:0.0.1
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service-registry
      - catalogue-service
      - rabbitmq