server:
  port: 8080

spring:
  application:
    name: CATALOGUE-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:microcredentials
    driverClassName: org.h2.Driver
    userName: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
